name: 'StandardJS lint checks'
description: 'Check that your code follows Standard Style'
branding:
  icon: 'code'
  color: 'yellow'
author: 'goto-bus-stop'
inputs:
  files:
    description: 'Globs to lint.'
    # let standard pick the default list
    # default: []
  version:
    description: 'Output format style, see https://eslint.org/docs/user-guide/formatters/. Default `stylish`.'
    required: true
    default: 'stylish'
  linter:
    description: 'Standard-compatible linter variant to use. ex. semistandard, happiness, doublestandard...'
    required: true
    default: 'standard'
  annotate:
    description: 'Annotate the diff UI with lint errors. Requires passing in env.GITHUB_TOKEN.'
    default: false
runs:
  using: 'node12'
  main: 'index.js'
